# This service requests re-localization using the output of the MOLA system
# state estimator, for example, from GNSS, odometry, and IMU data fusion.

# Request.
# No data needed.
---
# Result. False if there was no MOLA localization module
# accepting this request.
bool accepted
